// Generated by gencpp from file gz_ray_label_plugin/LabelPoints.msg
// DO NOT EDIT!


#ifndef GZ_RAY_LABEL_PLUGIN_MESSAGE_LABELPOINTS_H
#define GZ_RAY_LABEL_PLUGIN_MESSAGE_LABELPOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <gz_ray_label_plugin/LabelPoint.h>

namespace gz_ray_label_plugin
{
template <class ContainerAllocator>
struct LabelPoints_
{
  typedef LabelPoints_<ContainerAllocator> Type;

  LabelPoints_()
    : points()
    , px(0.0)
    , py(0.0)
    , pz(0.0)
    , dx(0.0)
    , dy(0.0)
    , dz(0.0)  {
    }
  LabelPoints_(const ContainerAllocator& _alloc)
    : points(_alloc)
    , px(0.0)
    , py(0.0)
    , pz(0.0)
    , dx(0.0)
    , dy(0.0)
    , dz(0.0)  {
  (void)_alloc;
    }



   typedef std::vector< ::gz_ray_label_plugin::LabelPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::gz_ray_label_plugin::LabelPoint_<ContainerAllocator> >> _points_type;
  _points_type points;

   typedef float _px_type;
  _px_type px;

   typedef float _py_type;
  _py_type py;

   typedef float _pz_type;
  _pz_type pz;

   typedef float _dx_type;
  _dx_type dx;

   typedef float _dy_type;
  _dy_type dy;

   typedef float _dz_type;
  _dz_type dz;





  typedef boost::shared_ptr< ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator> const> ConstPtr;

}; // struct LabelPoints_

typedef ::gz_ray_label_plugin::LabelPoints_<std::allocator<void> > LabelPoints;

typedef boost::shared_ptr< ::gz_ray_label_plugin::LabelPoints > LabelPointsPtr;
typedef boost::shared_ptr< ::gz_ray_label_plugin::LabelPoints const> LabelPointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator1> & lhs, const ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points &&
    lhs.px == rhs.px &&
    lhs.py == rhs.py &&
    lhs.pz == rhs.pz &&
    lhs.dx == rhs.dx &&
    lhs.dy == rhs.dy &&
    lhs.dz == rhs.dz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator1> & lhs, const ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gz_ray_label_plugin

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ded0ab792e6fc382d669b9d328e650f";
  }

  static const char* value(const ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ded0ab792e6fc38ULL;
  static const uint64_t static_value2 = 0x2d669b9d328e650fULL;
};

template<class ContainerAllocator>
struct DataType< ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gz_ray_label_plugin/LabelPoints";
  }

  static const char* value(const ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "LabelPoint[] points\n"
"float32 px\n"
"float32 py\n"
"float32 pz\n"
"float32 dx\n"
"float32 dy\n"
"float32 dz\n"
"================================================================================\n"
"MSG: gz_ray_label_plugin/LabelPoint\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"int32 index\n"
"float64 dist\n"
"string entityName\n"
;
  }

  static const char* value(const ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
      stream.next(m.px);
      stream.next(m.py);
      stream.next(m.pz);
      stream.next(m.dx);
      stream.next(m.dy);
      stream.next(m.dz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LabelPoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gz_ray_label_plugin::LabelPoints_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::gz_ray_label_plugin::LabelPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "px: ";
    Printer<float>::stream(s, indent + "  ", v.px);
    s << indent << "py: ";
    Printer<float>::stream(s, indent + "  ", v.py);
    s << indent << "pz: ";
    Printer<float>::stream(s, indent + "  ", v.pz);
    s << indent << "dx: ";
    Printer<float>::stream(s, indent + "  ", v.dx);
    s << indent << "dy: ";
    Printer<float>::stream(s, indent + "  ", v.dy);
    s << indent << "dz: ";
    Printer<float>::stream(s, indent + "  ", v.dz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GZ_RAY_LABEL_PLUGIN_MESSAGE_LABELPOINTS_H
