# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from gz_ray_label_plugin/LabelPoints.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import gz_ray_label_plugin.msg

class LabelPoints(genpy.Message):
  _md5sum = "8df55850541ba2b90a87120a4b1cc925"
  _type = "gz_ray_label_plugin/LabelPoints"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """LabelPoint[] points
float32 scaling = 0.15
float32 start_z = 0.5
int32 rating = 800
bool showMarker = 0
================================================================================
MSG: gz_ray_label_plugin/LabelPoint
float32 x
float32 y
float32 z
int32 index
float64 dist
string entityName"""
  # Pseudo-constants
  scaling = 0.15
  start_z = 0.5
  rating = 800
  showMarker = False

  __slots__ = ['points']
  _slot_types = ['gz_ray_label_plugin/LabelPoint[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       points

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LabelPoints, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.points is None:
        self.points = []
    else:
      self.points = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.points:
        _x = val1
        buff.write(_get_struct_3fid().pack(_x.x, _x.y, _x.z, _x.index, _x.dist))
        _x = val1.entityName
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.points is None:
        self.points = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.points = []
      for i in range(0, length):
        val1 = gz_ray_label_plugin.msg.LabelPoint()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z, _x.index, _x.dist,) = _get_struct_3fid().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.entityName = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.entityName = str[start:end]
        self.points.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.points:
        _x = val1
        buff.write(_get_struct_3fid().pack(_x.x, _x.y, _x.z, _x.index, _x.dist))
        _x = val1.entityName
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.points is None:
        self.points = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.points = []
      for i in range(0, length):
        val1 = gz_ray_label_plugin.msg.LabelPoint()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z, _x.index, _x.dist,) = _get_struct_3fid().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.entityName = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.entityName = str[start:end]
        self.points.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3fid = None
def _get_struct_3fid():
    global _struct_3fid
    if _struct_3fid is None:
        _struct_3fid = struct.Struct("<3fid")
    return _struct_3fid
