// Generated by gencpp from file gz_dynamic_colors/DColor.msg
// DO NOT EDIT!


#ifndef GZ_DYNAMIC_COLORS_MESSAGE_DCOLOR_H
#define GZ_DYNAMIC_COLORS_MESSAGE_DCOLOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gz_dynamic_colors
{
template <class ContainerAllocator>
struct DColor_
{
  typedef DColor_<ContainerAllocator> Type;

  DColor_()
    : r(0.0)
    , g(0.0)
    , b(0.0)
    , a(0.0)  {
    }
  DColor_(const ContainerAllocator& _alloc)
    : r(0.0)
    , g(0.0)
    , b(0.0)
    , a(0.0)  {
  (void)_alloc;
    }



   typedef float _r_type;
  _r_type r;

   typedef float _g_type;
  _g_type g;

   typedef float _b_type;
  _b_type b;

   typedef float _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::gz_dynamic_colors::DColor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gz_dynamic_colors::DColor_<ContainerAllocator> const> ConstPtr;

}; // struct DColor_

typedef ::gz_dynamic_colors::DColor_<std::allocator<void> > DColor;

typedef boost::shared_ptr< ::gz_dynamic_colors::DColor > DColorPtr;
typedef boost::shared_ptr< ::gz_dynamic_colors::DColor const> DColorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gz_dynamic_colors::DColor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gz_dynamic_colors::DColor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gz_dynamic_colors::DColor_<ContainerAllocator1> & lhs, const ::gz_dynamic_colors::DColor_<ContainerAllocator2> & rhs)
{
  return lhs.r == rhs.r &&
    lhs.g == rhs.g &&
    lhs.b == rhs.b &&
    lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gz_dynamic_colors::DColor_<ContainerAllocator1> & lhs, const ::gz_dynamic_colors::DColor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gz_dynamic_colors

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gz_dynamic_colors::DColor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gz_dynamic_colors::DColor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gz_dynamic_colors::DColor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gz_dynamic_colors::DColor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gz_dynamic_colors::DColor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gz_dynamic_colors::DColor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gz_dynamic_colors::DColor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a29a96539573343b1310c73607334b00";
  }

  static const char* value(const ::gz_dynamic_colors::DColor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa29a96539573343bULL;
  static const uint64_t static_value2 = 0x1310c73607334b00ULL;
};

template<class ContainerAllocator>
struct DataType< ::gz_dynamic_colors::DColor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gz_dynamic_colors/DColor";
  }

  static const char* value(const ::gz_dynamic_colors::DColor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gz_dynamic_colors::DColor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 r\n"
"float32 g\n"
"float32 b\n"
"float32 a\n"
;
  }

  static const char* value(const ::gz_dynamic_colors::DColor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gz_dynamic_colors::DColor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.r);
      stream.next(m.g);
      stream.next(m.b);
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DColor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gz_dynamic_colors::DColor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gz_dynamic_colors::DColor_<ContainerAllocator>& v)
  {
    s << indent << "r: ";
    Printer<float>::stream(s, indent + "  ", v.r);
    s << indent << "g: ";
    Printer<float>::stream(s, indent + "  ", v.g);
    s << indent << "b: ";
    Printer<float>::stream(s, indent + "  ", v.b);
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GZ_DYNAMIC_COLORS_MESSAGE_DCOLOR_H
